/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salondebelleza.appdesktop;

/**
 *
 * @author Usuario
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); //Coloca la pantalla al inicio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meInicio = new javax.swing.JMenuBar();
        meMantenimiento = new javax.swing.JMenu();
        meRol = new javax.swing.JMenuItem();
        meUsuario = new javax.swing.JMenuItem();
        meServicio = new javax.swing.JMenuItem();
        meCliente = new javax.swing.JMenuItem();
        meCambiarPassword = new javax.swing.JMenu();
        meCambiarUsuario = new javax.swing.JMenu();
        meSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meMantenimiento.setMnemonic('M');
        meMantenimiento.setText("Mantenimiento");

        meRol.setMnemonic('R');
        meRol.setText("Rol");
        meRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meRolActionPerformed(evt);
            }
        });
        meMantenimiento.add(meRol);

        meUsuario.setMnemonic('U');
        meUsuario.setText("Usuario");
        meUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meUsuarioActionPerformed(evt);
            }
        });
        meMantenimiento.add(meUsuario);

        meServicio.setText("Servicio");
        meServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meServicioActionPerformed(evt);
            }
        });
        meMantenimiento.add(meServicio);

        meCliente.setText("Cliente");
        meCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meClienteActionPerformed(evt);
            }
        });
        meMantenimiento.add(meCliente);

        meInicio.add(meMantenimiento);

        meCambiarPassword.setMnemonic('P');
        meCambiarPassword.setText(" CambiarPassword");
        meCambiarPassword.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                meCambiarPasswordMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        meInicio.add(meCambiarPassword);

        meCambiarUsuario.setMnemonic('C');
        meCambiarUsuario.setText("CambiarUsuario");
        meCambiarUsuario.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                meCambiarUsuarioMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        meInicio.add(meCambiarUsuario);

        meSalir.setMnemonic('S');
        meSalir.setText("Salir");
        meSalir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                meSalirMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        meInicio.add(meSalir);

        setJMenuBar(meInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meCambiarPasswordMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_meCambiarPasswordMenuSelected
        // TODO add your handling code here:
        FrmCambiarPassword frmCambiarPassword = new FrmCambiarPassword(this);
        frmCambiarPassword.setVisible(true);
        frmCambiarPassword.setAlwaysOnTop(true);
        this.setEnabled(false);
    }//GEN-LAST:event_meCambiarPasswordMenuSelected

    private void meCambiarUsuarioMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_meCambiarUsuarioMenuSelected
        // TODO add your handling code here:
        this.setVisible(false);
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
    }//GEN-LAST:event_meCambiarUsuarioMenuSelected

    private void meSalirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_meSalirMenuSelected
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        System.exit(0);      //Cerrar el sistema, usar para cerrar el sistema completamente.
    }//GEN-LAST:event_meSalirMenuSelected

    private void meRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meRolActionPerformed
        // TODO add your handling code here:
        FrmRolLec frmRolLec = new FrmRolLec(this);
        frmRolLec.setVisible(true);
         this.setEnabled(false);

    }//GEN-LAST:event_meRolActionPerformed

    private void meUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meUsuarioActionPerformed
        // TODO add your handling code here:
        FrmUsuarioLec frmUsuarioLec = new FrmUsuarioLec(this);
        frmUsuarioLec.setVisible(true);
        this.setEnabled(false);
        //this.setEnabled(false);
    }//GEN-LAST:event_meUsuarioActionPerformed

    private void meServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meServicioActionPerformed
        // TODO add your handling code here:
        FrmServicioLec frmServicioLec = new FrmServicioLec(this);
        frmServicioLec.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_meServicioActionPerformed

    private void meClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meClienteActionPerformed
        // TODO add your handling code here:
       FrmClienteLec frmClienteLec = new FrmClienteLec(this);
       frmClienteLec.setVisible(true);
      this.setEnabled(false);
    }//GEN-LAST:event_meClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu meCambiarPassword;
    private javax.swing.JMenu meCambiarUsuario;
    private javax.swing.JMenuItem meCliente;
    private javax.swing.JMenuBar meInicio;
    private javax.swing.JMenu meMantenimiento;
    private javax.swing.JMenuItem meRol;
    private javax.swing.JMenu meSalir;
    private javax.swing.JMenuItem meServicio;
    private javax.swing.JMenuItem meUsuario;
    // End of variables declaration//GEN-END:variables
}
